apiVersion: v2
name: tributech-devops-chart
description: Umbrella Helm chart for Tributech DevOps assignment
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.5.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: keycloak
    version: "17.3.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: keycloak.enabled
  - name: pgadmin4
    version: "1.13.9"
    repository: "https://helm.runix.net"
    condition: pgadmin.enabled
  - name: website
    version: "*"
    repository: "file://charts/website"
    condition: website.enabled