apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{ include "pgadmin.labels" . | nindent 4 }}
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.admin.email | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.admin.password | quote }}