apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.admin.email | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.admin.password | quote }}