apiVersion: v1
kind: Secret
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.keycloak.clientSecret | b64enc }}