apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: tributech-ui-oauth-sample:latest
          ports:
            - containerPort: 80
          env:
            - name: KEYCLOAK_URL
              value: "http://keycloak.local/auth"
            - name: DATABASE_URL
              value: "postgresql://keycloak:keycloakpassword@postgresql:5432/keycloakdb"