apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    app: {{ include "website.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "website.fullname" . }}
                port:
                  number: 80