apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: {{ .Values.keycloak.postgresql.host | quote }}
            - name: DB_PORT
              value: {{ .Values.keycloak.postgresql.port | quote }}
            - name: DB_DATABASE
              value: {{ .Values.keycloak.postgresql.database | quote }}
            - name: DB_USER
              value: {{ .Values.keycloak.postgresql.username | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.keycloak.postgresql.password | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP