apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    app: {{ include "keycloak.name" . }}
    chart: {{ include "keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "keycloak.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "keycloak.name" . }}
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_VENDOR
              value: "POSTGRES"
            - name: DB_ADDR
              value: {{ .Values.postgresql.host }}
            - name: DB_DATABASE
              value: {{ .Values.postgresql.database }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.fullname" . }}-postgresql
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.fullname" . }}-postgresql
                  key: password
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}