apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app: postgresql
type: Opaque
data:
  username: a2V5Y2xvYWs= # Base64-encoded value of "keycloak"
  password: a2V5Y2xvYWtwYXNzd29yZA== # Base64-encoded value of "keycloakpassword"
  database: a2V5Y2xvYWtkYg== # Base64-encoded value of "keycloakdb"