apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  postgres-user: {{ .Values.postgresql.username | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
  postgres-db: {{ .Values.postgresql.database | b64enc | quote }}