# File: /tributech-devops-assignment/helm-chart/charts/keycloak/values.yaml

keycloak:
  image:
    repository: bitnami/keycloak
    tag: latest
  replicaCount: 1
  service:
    enabled: true
    type: ClusterIP
    port: 8080
    annotations: {}
  ingress:
    enabled: true
    hostname: keycloak.local
    path: /
    pathType: ImplementationSpecific
    annotations:
      kubernetes.io/ingress.class: nginx
  auth:
    adminUser: admin
    adminPassword: adminpassword
  database:
    host: postgresql
    port: 5432
    user: keycloak
    password: keycloakpassword
    name: keycloakdb
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10