# File: /tributech-devops-assignment/tributech-devops-assignment/helm-chart/charts/pgadmin/values.yaml

pgadmin:
  ingress:
    enabled: true
    hostname: pgadmin.local
  admin:
    email: admin@example.com
    password: adminpassword
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  image:
    repository: dpage/pgadmin4
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"