name: postgresql
version: 0.1.0
description: A Helm chart for Kubernetes to deploy PostgreSQL
type: application
keywords:
  - postgresql
  - database
  - helm
  - kubernetes
maintainers:
  - name: Your Name
    email: your.email@example.com
sources:
  - https://www.postgresql.org/
dependencies: []