database:
  name: keycloakdb
  user: keycloak
  password: keycloakpassword
  port: 5432
  host: postgresql.local

replicaCount: 1

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  enabled: true
  type: ClusterIP
  port: 5432

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - host: postgresql.local
      paths:
        - /
  tls: []